#!/usr/bin/env python3
"""
Golden City Panel Detection Instructions
Since AnComicsViewer is already running, follow these steps:
"""

def main():
    print("=== Golden City Comic - Testing Instructions ===")
    print()
    print("🎯 MANUAL TESTING STEPS:")
    print()
    print("1. In the running AnComicsViewer window:")
    print("   - Press Ctrl+O (or click 📂)")
    print("   - Select: 'Golden City - T01 - Pilleurs d'épaves.pdf'")
    print()
    print("2. Set up for Franco-Belge comics:")
    print("   - Click ⚙️ (settings menu)")
    print("   - Go to Presets → Franco-Belge")
    print("   - This optimizes detection for Franco-Belgian comic style")
    print()
    print("3. Enable panel detection:")
    print("   - Press Ctrl+2 (or click ▦) to toggle panel overlay")
    print("   - You should see colored rectangles around detected panels")
    print()
    print("4. Navigate through panels:")
    print("   - Press N for next panel")
    print("   - Press Shift+N for previous panel")
    print("   - The view will automatically frame each panel")
    print()
    print("5. Test ML detector (optional):")
    print("   - Click ⚙️ → Detector → Load ML weights…")
    print("   - Select: yolov8n-seg.pt")
    print("   - Click ⚙️ → Detector → YOLOv8 Seg (ML)")
    print("   - Compare detection results")
    print()
    print("6. Fine-tune detection (if needed):")
    print("   - Click ⚙️ → Advanced tuning…")
    print("   - Adjust parameters in real-time")
    print("   - Click Apply to see changes immediately")
    print()
    print("📊 EXPECTED RESULTS:")
    print("- Franco-Belge preset should work well for Golden City")
    print("- Typical BD page has 4-8 panels in structured layout")
    print("- Detection should handle irregular panel shapes")
    print("- Title areas should be filtered out automatically")
    print()
    print("🔧 TROUBLESHOOTING:")
    print("- If few panels detected: try lower Detection DPI (150)")
    print("- If too many false positives: increase minimum panel size")
    print("- If panels missed: reduce adaptive threshold parameters")
    print()
    print("📝 NOTE: Golden City is a classic Franco-Belgian comic series")
    print("by Daniel Pecqueur and Nicolas Malfin, perfect for testing")
    print("traditional BD panel detection algorithms!")

if __name__ == "__main__":
    main()
