#!/bin/bash
# Script de démonstration du post-traitement raffiné

echo "🎯 Démonstration du post-traitement raffiné AnComicsViewer"
echo "=========================================================="
echo ""
echo "Le post-traitement raffiné apporte les améliorations suivantes:"
echo ""
echo "✅ FILTRAGE INTELLIGENT:"
echo "   • Seuils de confiance par classe (panels vs balloons)"
echo "   • Filtrage par taille minimale/maximale"
echo "   • Exclusion des détections en bord de page"
echo "   • NMS séparée par classe (évite la suppression inter-classe)"
echo ""
echo "✅ RÈGLES SÉMANTIQUES:"
echo "   • Les balloons doivent être attachés à des panels"
echo "   • Limitation du nombre total de détections"
echo "   • Priorisation par taille et confiance"
echo ""
echo "✅ MÉTRIQUES DE QUALITÉ:"
echo "   • Score de qualité automatique (0-1)"
echo "   • Détection des overlaps et severe overlaps"
echo "   • Export JSON optionnel pour analyse"
echo ""

echo "🧪 Test du post-traitement..."
python3 test_refined_postproc.py

echo ""
echo "📊 Configuration utilisée:"
echo "-------------------------"
echo "Paramètres clés du YAML (config/detect_with_merge.yaml):"
echo ""
echo "# Seuils par classe"
echo "panel_conf: $(grep '^panel_conf:' config/detect_with_merge.yaml | cut -d' ' -f2)"
echo "balloon_conf: $(grep '^balloon_conf:' config/detect_with_merge.yaml | cut -d' ' -f2)"
echo ""
echo "# NMS par classe"
echo "panel_nms_iou: $(grep '^panel_nms_iou:' config/detect_with_merge.yaml | cut -d' ' -f2)"
echo "balloon_nms_iou: $(grep '^balloon_nms_iou:' config/detect_with_merge.yaml | cut -d' ' -f2)"
echo ""
echo "# Limites de quantité"
echo "max_panels: $(grep '^max_panels:' config/detect_with_merge.yaml | cut -d' ' -f2)"
echo "max_balloons: $(grep '^max_balloons:' config/detect_with_merge.yaml | cut -d' ' -f2)"
echo ""
echo "# Attachement balloon→panel"
echo "balloon_min_overlap_panel: $(grep '^balloon_min_overlap_panel:' config/detect_with_merge.yaml | cut -d' ' -f2)"

echo ""
echo "💡 UTILISATION:"
echo "---------------"
echo ""
echo "Pour tester avec un vrai PDF:"
echo ""
echo "1. Avec métriques export:"
echo "   python3 main.py --config config/detect_with_merge.yaml \\"
echo "                   --metrics-out metrics.json \\"
echo "                   --debug-detect"
echo ""
echo "2. Avec debug visuel:"
echo "   python3 main.py --debug-detect --save-debug-overlays debug"
echo ""
echo "3. Traitement batch (script):"
echo "   for page in {0..5}; do"
echo "     python3 main.py --page \$page --metrics-out batch.json"
echo "   done"
echo ""

echo "🎯 RÉSULTATS ATTENDUS:"
echo "----------------------"
echo "• ⬇️  Réduction significative des détections parasites"
echo "• 🎈 Balloons mieux attachés aux panels"
echo "• 📊 Score de qualité plus élevé"
echo "• 🖼️  Overlays de debug plus propres"
echo "• 📈 Métriques détaillées en JSON"

echo ""
echo "✅ Post-traitement raffiné prêt à utiliser!"
